name: golang lint

on:
  workflow_call:
    secrets:
      CICD_DOCKER_BUILD_PAT:
        required: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ vars.GOPRIVATE }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.CICD_DOCKER_BUILD_PAT }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: git config --global url.https://$GITHUB_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
